project:
  type: website
  output-dir: docs
  resources: 
    - styles.css
    - images/


website:
  title: "講義資料"     

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

