project:
  type: website
  output-dir: docs

website:
  title: "講義資料"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: labor_intro.qmd
        text: "はじめに"     

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



