project:
  type: website
  output-dir: docs
  resources: 
    - styles.css
    - images/
    - robots.txt


website:
  title: "講義資料"     

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

watch:
  input: true   # 入力ファイルの変更を監視
  output: true  # 出力ファイルも再構築