---
title: "マクロ経済学から見る労働経済学"
format: html
---

> 本資料は、大森義明・永瀬伸子（2021）『労働経済学をつかむ』（有斐閣）　を参考に作成しています。
> 授業目的に合わせて一部構成や表現を調整しています。

これまでの章では、労働者や企業がどのように合理的な意思決定を行うかという**ミクロ経済学的な視点**から労働経済を見てきました。  
この章では、そのような意思決定の積み重ねが**労働市場全体**にどのような影響を及ぼすのかを、**マクロ経済学的な観点**から分析していきます。

# 転職・就職

## 転職の決定と職探し

### ジョブ・サーチの理論

**ジョブ・サーチ**とは、職探しのことです。まずは、大学生の就職活動の例を通して、職探しのプロセスでは、何に基づいてどのような意思決定が行われているかを見ていきましょう。


::: {.callout-tip appearance="default" icon="false"}
## 就職浪人をしようかどうか迷うタロウの例

大学4回生のタロウは、内定をもらった第2志望の会社に就職するか、就職浪人をして第1希望の会社への就職を目指すか悩んでいます。

- 第1希望
  - 生涯賃金4億円
  - 内定なし
- 第2希望
  - 生涯賃金3億円
  - 内定あり

※生涯賃金以外の面での魅力度は同じ

タロウはすでに単位を取り終え、卒論を提出すれば卒業できる状態です。

:::

このとき、今年第2志望の会社に就職するべきか、1年留年して、来年第1希望の会社に就職できるように就職活動をやり直すべきか、考えてみます。

#### 追加的な1年間の就職活動の純便益

**就職活動の費用**

- 留年 $\rightarrow$ 1年分の学費100万円※ただし授業は取らないので得られるものはない
- 就職活動の直接費用10万円（交通費や携帯代など）
- 第2志望の会社に就職していれば得られたであろう生涯賃金3億円（**機会費用**）

$\rightarrow$ 計3億110万円

**就職活動の便益**

- （第1志望の会社に就職すれば）生涯賃金3億9000万円
  - 上述した生涯賃金4億円は、今年就職し定年まで43年勤めたときの総所得
  - 留年すれば勤続年数は42年、この会社の65歳時の平均年収1000万円を取りそこなう
- （就職活動がうまくいかなければ）生涯賃金8000万円（塾講師のアルバイトを想定）

$\rightarrow$ 純便益は内定確率によって異なる

**就職成功** $\rightarrow$ **8890万円**（3億9000万円 $-$ 3億110万円）

**就職失敗** $\rightarrow$ **-2億2110万円**（8000万円 $-$ 3億110万円）

では、どのくらいの内定確率があれば就職活動を続けるべきでしょうか？求める確率を $P_{1}$ とすると、

$$
P_{1} \times 8890万円 - (1 -  P_{1}) \times 2億2110万円 = 0
$$

が成り立つ必要があります。つまり、

$$
\begin{align}
(8890万円 + 2億2110万円) \times P_{1} - 2億2110万円  =& 0 \\
3億1000万円 \times P_{1} =& 2億2110万円 \\
P_{1} \approx& 0.713 \\
\end{align}
$$

内定確率が71.3%を上回っている必要があります。

ただし、この考え方はリスクを伴う第1志望の内定から得られる純便益の期待値と、確実に得られる第2志望の内定から得られる純便益の期待値を中立的に捉えられる（**リスク中立的な態度を持つ**）人に当てはまる考え方です。中には、71.3%の内定確率があってもリスクをとって留年をすることに不安を覚える（**リスク回避的な態度を持つ**）人もいるかもしれません。リスク回避的な人が留年を受け入れるには、リスクを伴う第1志望の内定から得られる純便益の期待値が、確実に得られる第2志望の内定から得られる純便益の期待値を十分に上回る必要があります。

::: {.callout-important appearance="default" icon="false"}
## まとめ：就職活動を続けるために必要な内定確率

- **就職活動の純便益** $=$ **就職活動の便益** $-$ **就職活動の費用**
- **就職活動の費用** $=$ 直接費用（学費・活動費）$+$ **機会費用**
- **就職活動の便益** $=$ 就職活動が成功 or 失敗したときの生涯賃金

就職が成功したときの純便益を $\pi_{S}$、失敗したときの純便益を $\pi_{F}$ とすると、リスク中立的な態度を持つ人にとって就職活動を続けることが合理的になる内定確率 $P$ は、

$$
\begin{align}
P \pi_{S} + (1-P) \pi_{F} =& 0 \\
P =& \frac{-\pi_{F}}{\pi_{S} - \pi_{F}}
\end{align}
$$

:::

:::{.quizbox}

**確認クイズ：**  
あなたは内定をもらったアルバイトで1か月働くか（$月収4万円$）、内定を辞退し、来月憧れのアルバイト（$月収20万円$）に挑戦するか迷っています。アルバイト探しの直接費用は1万円です。内定を断ると今月の収入は0円になります。次の問いに答えなさい。

1. 憧れのアルバイトに内定したときの純便益はいくらか？  
   <input type="text" class="fill-in" id="quiz1a" placeholder="ここに入力">万円

2. アルバイト探しに失敗したときの純便益はいくらか？  
   <input type="text" class="fill-in" id="quiz1b" placeholder="ここに入力">万円

3. アルバイト探し続けることが合理的となるために必要な内定確率はいくらか？
   <input type="text" class="fill-in" id="quiz1c" placeholder="ここに入力">

<button onclick="showAnswer('jobsearch')">答えを見る</button>
<div id="jobsearch" class="answer" style="display:none; margin-top: 0.5em;">
1. 15万円（$= 20万円 - 4万円 - 1万円$）<br>
2. -5万円（$= 0円 - 4万円 - 1万円$）<br>
3. 約 0.25 （$P = 5/(15 + 5)$）
</div>

:::


ここからは、タロウが直面する環境が変わったときに、就職活動を続けることが合理的になる内定確率がどのように変化するかを分析しましょう。

##### Case 1：家業を継ぐことができるとき

就職活動がうまくいかなかったとき、タロウは家業を継ぐという第3の選択肢を取ることができるとします。家業を継いだ場合の生涯賃金は2億円程度だと分かっています。このことは、就職活動を続けて失敗したときの便益を変化させます。

このとき、就職活動を続けることの純便益は以下のようになります。

**就職成功** $\rightarrow$ **8890万円**（3億9000万円 $-$ 3億110万円）

**就職失敗** $\rightarrow$ **-1億110万円**（2億円 $-$ 3億110万円）

よって、就職活動を続けることが合理的になる内定確率は、以下の式を満たします。

$$
\begin{align}
P_{2} \times 8890万円 - (1 - P_{2}) \times 1億110万円 & 0 \\
(8890万円 + 1億110万円) \times P_{2} - 1億110万円 =& 0 \\
1億9000万円 \times P_{2} =& 1億110万円 \\
P_{2} \approx& 0.532 \\
\end{align}
$$

内定確率が53.2%を上回っている必要があります。

家業を継ぐという選択肢がなかったときの必要内定率71.3%よりも、かなり低い内定確率で就職活動を続けることが合理的になります。

ここで家業は、就職活動に失敗した際の**セーフティネット**（保護網）の役割を果たしています。家業がなければ、最悪の場合生涯賃金が0円になることすらあり得ますが、そうならずに済むのはタロウに家業を継ぐという選択肢があるからです。

セーフティネットは、タロウにとっての助けとなると同時に、就職活動期間を伸ばすという副作用もあります。

もし、家業を継ぐという選択肢がなければ、最悪の場合に生涯賃金は0円になります。このとき、就職活動を続けることが合理的になる内定確率は、

$$
\begin{align}
P_{3} \times 8890万円 - (1 - P_{3}) \times 3億110万円 & 0 \\
(8890万円 + 3億110万円) \times P_{3} - 3億110万円 =& 0 \\
3億9000万円 \times P_{3} =& 3億110万円 \\
P_{3} \approx& 0.772 \\
\end{align}
$$

内定確率が77.2%を上回っている必要があります。相当な自信がないと就職活動を続けることは合理的とは言えません。

家業を継ぐという選択肢がなければ、就職活動を辞め、第2志望の会社に就職するインセンティブが高まるのです。

多くの労働者にとっては、雇用保険の失業手当がセーフティネットの役割を果たします。

##### Case 2：第2志望の会社の生涯賃金が高いとき

現在のオファー（生涯賃金）の高さは、就職活動を短くします。もし、タロウが内定をもらった第2志望の会社の生涯賃金が、3億円ではなく3億5000万円であったらどうでしょうか。この変化は、就職活動を続けるときの機会費用を変化させます。

就職活動を続けることの純便益は以下のようになります。

**就職成功** $\rightarrow$ **3890万円**（3億9000万円 $-$ 3億5110万円）

**就職失敗** $\rightarrow$ **-1億5110万円**（2億円 $-$ 3億5110万円）

よって、就職活動を続けることが合理的になる内定確率は、以下の式を満たします。

$$
\begin{align}
P_{4} \times 3890万円 - (1 - P_{4}) \times 1億5110万円 & 0 \\
(3890万円 + 1億5110万円) \times P_{4} - 1億5110万円 =& 0 \\
1億9000万円 \times P_{4} =& 1億5110万円 \\
P_{4} \approx& 0.795 \\
\end{align}
$$

内定確率が79.5%を上回っていないと、就職活動を続けることは非合理的になってしまいます。この確率は、Case 1での確率53.2%よりもかなり高い確率です。

現在のオファーである第2志望の会社の生涯賃金が高くなると、就職活動を辞め、第2志望の会社に就職するインセンティブが高まるのです。

働いている労働者が職探しを始める場合には、現在の仕事の所得が現在のオファーとなります。現在の仕事の所得が低ければ、職探しをするインセンティブが高まり、離職しやすくなります。よって、所得の高い仕事をしている労働者は勤続年数が長くなり、所得が低いと勤続年数は短くなる傾向があります。

##### Case 3：第1志望の会社の生涯賃金が高いとき

Case 2とは逆に、第1志望の会社から期待できるオファー（生涯賃金）が高いことは、就職活動期間を延ばします。第1志望の会社の生涯賃金が3億9000万円ではなく4億5000万円であったらどうでしょうか。この変化は、就職活動を続けるときの便益を変化させます。

就職活動を続けることの純便益は以下のようになります。

**就職成功** $\rightarrow$ **1億4890万円**（4億5000万円 $-$ 3億110万円）

**就職失敗** $\rightarrow$ **-1億110万円**（2億円 $-$ 3億110万円）

よって、就職活動を続けることが合理的になる内定確率は、以下の式を満たします。

$$
\begin{align}
P_{5} \times 1億4890万円 - (1 - P_{5}) \times 1億110万円 & 0 \\
(1億4890万円 + 1億110万円) \times P_{5} - 1億110万円 =& 0 \\
2億5000万円 \times P_{5} =& 1億110万円 \\
P_{5} \approx& 0.404 \\
\end{align}
$$

内定確率が40.4%を上回っていれば、就職活動を続けることは合理的になります。この確率は、生涯賃金が3億9000万であるときの確率53.2%よりも低く、期待オファーが高まると、第2志望の内定を辞退し、就職活動を続けるインセンティブが高まることが分かります。

以上のCase 1 ～ Case 3 より[^mamou]、ジョブ・サーチの理論から得られる示唆をまとめると次のようになります。

[^mamou]: 自身の内定確率を見積もるときには、就職活動を1年間延長することによる人的資本の摩耗や、汚名効果を考慮する必要があります。1年間留年をして就職活動をしても、その間に授業を受けるわけではないので、新しいスキルが身につかないことはもちろん、現在身につけている知識やスキルを失うことすらもあり得ます。このことを**人的資本の摩耗**と言います。また、留年したことは就職活動先の会社に知られてしまうので、能力が低くて卒業できなかったか、内定がもらえなかったかのいずれかではないかと思われるでしょう。就職活動期間の長期化に伴う人的資本の摩耗や汚名効果によって、1年後の内定率は下がるかもしれません。

::: {.callout-note appearance="default" icon="false"}
## ジョブ・サーチの理論

- **経験年数が長い労働者は賃金が高い**
  - 経験年数が長い労働者は長い期間にわたってジョブ・サーチをしており、他の仕事のオファーを受けるたびに最も高い賃金を受け入れてきたはずであるため
- **勤続年数が長い労働者は賃金が高い**
  - 現在のオファーが高いからこそ、それを上回るオファーが来ず、結果として勤続年数が長くなったと考えられるため
- **経験年数・勤続年数が長い労働者は離職・転職率が低い**
  - このような労働者は賃金が高い傾向にあるため

:::




### オン・ザ・ジョブ・サーチ

### ジョブ・マッチングの理論


## 労働市場の流動性

### 日本の転職の状況

### 離職の起こりやすさ

### 労働市場の流動化と解雇規制



# 賃金格差

## 賃金格差が生じる要因

### さまざまな賃金格差

### 賃金格差を生じさせる要因

### 賃金格差をもたらす測定可能な要因に関する経済理論

### 賃金格差に関する測定不可能な要因

### 差別による賃金格差を縮小するための方法


## グループ間の賃金格差

### さまざまなグループ間の賃金格差



# 失業と不安定雇用

## 失業のストックとフロー

### 失業率とは

### 労働力のフロー分析

### マクロ経済と失業率の関係


## 不本意な非正規雇用

### 非正規雇用の拡大

### 安定雇用への入口？

### 不安定な非正規労働

### 非正社員の安定性を確保するための政策


[講義資料に戻る](index.html)

{{< include quiz.html >}}

