name: Deploy Markdown to GitHub Pages

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # Pandocがインストールされているか確認
      - name: Install Pandoc
        run: |
          if ! command -v pandoc &> /dev/null
          then
            echo "Pandoc is not installed. Installing Pandoc..."
            # Pandocをインストール
            sudo apt-get update
            sudo apt-get install -y pandoc
          else
            echo "Pandoc is already installed."
          fi
          pandoc --version

      # マークダウンファイルをHTMLに変換
      - name: Markdown to HTML
        run: |
          for file in docs/source/*.md; do
            echo "$file"
            pandoc "$file" -o "docs/$(basename "$file%.md".html)" --standalone --metadata title="" --css=https://cdn.jsdelivr.net/npm/water.css@2/out/water.min.css
          done

      # ファイル名リストを取得
      - name: List files
        run: git ls-tree -r HEAD --name-only
      
      # 変換したファイルをプッシュ（変更があったときのみ）
      - name: Commit and push the HTML file
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git diff --exit-code docs/index.html
          if [ $? -eq 1 ]; then
            git add docs/index.html
            git commit -m "Update HTML"
            git push
          else
            echo "No changes detected, skipping commit."
          fi
          
