name: Deploy Markdown to GitHub Pages

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc
