name: Deploy Markdown to GitHub Pages

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # Pandocがインストールされているか確認
      - name: Install Pandoc
        run: |
          if ! command -v pandoc &> /dev/null
          then
            echo "Pandoc is not installed. Installing Pandoc..."
            # Pandocをインストール
            sudo apt-get update
            sudo apt-get install -y pandoc
          else
            echo "Pandoc is already installed."
          fi
          pandoc --version

      # マークダウンファイルをHTMLに変換
      - name: Markdown to HTML
        run: |
          for file in docs/source/*.md; do
            filename=$(basename "$file" .md) 
            echo "Converting $filename"
            pandoc "$file" -o "docs/$filename.html" --standalone --metadata title="text" --css=https://cdn.jsdelivr.net/npm/water.css@2/out/water.min.css
          done
      
      # 変換したファイルをプッシュ（変更があったときのみ）
      - name: Commit and push the HTML file
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          if [[ $(git status --porcelain docs/*.html) ]]; then
            echo "Comitting changes."
            git add docs/*.html
            git commit -m "Update HTML files"
            git push
          else
            echo "No changes in HTML files."
          fi
          
      # ファイル名リストを取得
      - name: List files
        run: git ls-tree -r HEAD --name-only
          
