name: Deploy Markdown to GitHub Pages

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # Pandocをインストール
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      # Pandocのインストールを確認
      - name: Check Pandoc installation
        run: pandoc --version

      # ファイル名リストを取得
      - name: List files
        run: git ls-tree -r HEAD --name-only

      # マークダウンファイルをHTMLに変換
      - name: Markdown to HTML
        run: pandoc docs/index.md -o docs/site/index.html

      # 
      - name: Commit and push the HTML file
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/site/index.html
          git commit -m "Add HTML"
          git push
