name: Deploy Markdown to GitHub Pages

on:
  push:
    branches:
      - main  # mainブランチへのpushでトリガー
    paths:
      - 'docs/**/*.md'  # docsフォルダ内のマークダウンファイルが変更された時にトリガー

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    
    steps:
      # リポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # Pandocをインストール
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      # マークダウンファイルをHTMLに変換
      - name: Convert Markdown to HTML
        run: |
          mkdir -p docs/site
          for file in docs/**/*.md; do
            base_name=$(basename "$file" .md)
            pandoc "$file" -o "docs/site/${base_name}.html" \
            --standalone \
            --metadata title="" \
            --css=https://cdn.jsdelivr.net/npm/water.css@2/out/water.min.css \
            --shift-heading-level-by=-1
          done

      # GitHub Pagesにデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/site
