name: Deploy Markdown to GitHub Pages

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # Pandocをインストール
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      # Pandocのインストールを確認
      - name: Check Pandoc installation
        run: pandoc --version

      # マークダウンファイルをHTMLに変換
      - name: Markdown to HTML
        run: pandoc docs/index.md -o docs/site/index.html

